name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m nltk.downloader punkt stopwords
      
    - name: Run tests
      run: |
        if [ -d "tests" ]; then
          PYTHONPATH=src python -m unittest discover tests
        else
          echo "No tests directory found, skipping tests."
        fi
